name: Build

on:
  push:
    branches:
      - main

jobs:
  release:
    name: build and release
    runs-on: windows-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build Electron App for Windows
        run: yarn run build:win
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN_PUB }}

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Windows
          path: |
            release/**
